# Generated by Django 5.2.5 on 2025-08-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_category_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
