# Generated by Django 5.2.5 on 2025-08-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(null=True, upload_to="static/uploads"),
        ),
    ]
