# Generated by Django 5.2.5 on 2025-08-27 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_cart_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
    ]
